<?php
return [
 'nav'=>['title'=>'Gaming Hub','games'=>'Games','directory_settings'=>'Directory Settings','public_data'=>'Public Data','package_manager'=>'Package Manager'],
 'permissions'=>['games_view'=>'View the Gaming Hub game registry','games_manage'=>'Manage the Gaming Hub game registry','servers_view'=>'View game servers','servers_manage'=>'Manage game servers','providers_view'=>'View server providers','providers_manage'=>'Manage server providers','settings_manage'=>'Manage the public Games directory settings'],
 'games'=>['title'=>'Games','create'=>'Create Game','edit'=>'Edit Game'],
 'servers'=>['title'=>'Servers','for_game'=>'Servers for :game','create'=>'Create Server','edit'=>'Edit Server'],
 'providers'=>['title'=>'Providers','for_game'=>'Providers for :game','for_server'=>'Providers for :server','create'=>'Create Provider','edit'=>'Edit Provider'],
 'settings'=>['title'=>'Games Directory Settings','saved'=>'Directory settings saved.','page_title'=>'Page title','description'=>'Page description','description_help'=>'Plain text only. Line breaks are preserved and HTML is escaped.','columns'=>'Grid columns','density'=>'Card density','width'=>'Container width','show_description'=>'Show game descriptions','show_status'=>'Show status','show_provider_message'=>'Show provider message','show_button'=>'Show View Game button','show_count'=>'Show enabled-game count','show_servers'=>'Show Servers on Game page','game_page_title'=>'Game Page Settings','server_density'=>'Server card density','server_columns'=>'Server grid columns','show_server_descriptions'=>'Show server descriptions','game_page_show_status'=>'Show server status','game_page_show_provider_message'=>'Show provider message','show_join_button'=>'Show Join button','show_address'=>'Show address','show_game_navigation'=>'Show right-side game navigation','fallback'=>'No-banner fallback','values'=>['compact'=>'Compact','standard'=>'Standard','normal'=>'Normal','wide'=>'Wide','full'=>'Full','fallback_compact'=>'Compact card without media','fallback_media'=>'Media placeholder','address_hidden'=>'Hidden','address_hostname'=>'Hostname only','address_hostname_and_port'=>'Hostname and port']],
 'manual'=>['name'=>'Manual','description'=>'A local, administrator-maintained server status. No network requests are made.','status'=>'Status','display_message'=>'Optional display message'],
 'fields'=>['order'=>'Order','game'=>'Game','server'=>'Server','name'=>'Name','short_name'=>'Short name','slug'=>'Slug','description'=>'Legacy description','short_description'=>'Short description','long_description'=>'Long description','icon_url'=>'Icon URL','banner_url'=>'Banner URL','accent_color'=>'Accent color','enabled'=>'Enabled','public'=>'Public','sort_order'=>'Sort order','hostname'=>'Hostname','display_port'=>'Display port','join_url'=>'Join URL','icon_media_id'=>'Icon media ID','cover_media_id'=>'Cover media ID','provider_type'=>'Provider type','actions'=>'Actions'],
 'actions'=>['create'=>'Create Game','create_server'=>'Add Server','create_provider'=>'Add Provider','save'=>'Save','cancel'=>'Cancel','back_games'=>'Back to games','back_servers'=>'Back to servers'],
 'messages'=>['created'=>'Game created.','updated'=>'Game updated.','deleted'=>'Game deleted.','empty'=>'No games have been registered.','confirm_delete'=>'Delete this game permanently?'],
 'server_messages'=>['created'=>'Server created.','updated'=>'Server updated.','deleted'=>'Server deleted.','duplicated'=>'Server metadata duplicated. Provider instances were not copied.','empty'=>'No servers are registered for this game.','confirm_delete'=>'Delete this server and its provider assignments permanently?'],
 'provider_messages'=>['created'=>'Provider created.','updated'=>'Provider updated.','moved'=>'Provider priority updated.','deleted'=>'Provider deleted.','empty'=>'No providers are assigned to this server.','no_types'=>'No provider types are currently registered and available.','confirm_delete'=>'Delete this provider permanently?','move_boundary'=>'This provider is already at the requested boundary.','create_failed'=>'The provider could not be created.','update_failed'=>'The provider could not be updated.','toggle_failed'=>'The provider enabled state could not be changed.','move_failed'=>'The provider priority could not be changed.','delete_failed'=>'The provider could not be deleted. Its configuration and related connections were left unchanged.'],
 'validation'=>['unknown_type'=>'The selected provider type is not registered.','unavailable_type'=>'The selected provider type is not currently available.','configuration_object'=>'Configuration must be a keyed object, not a list.','unknown_keys'=>'Unknown configuration keys: :keys'],
];
