@extends('admin.layouts.admin')
@section('title',trans('gaming-hub-core::admin.servers.for_game',['game'=>$game->name]))
@section('content')<div class="card"><div class="card-body"><div class="d-flex justify-content-between mb-3"><div><h1 class="h4 mb-1">{{ trans('gaming-hub-core::admin.servers.for_game',['game'=>$game->name]) }}</h1><a href="{{ route('gaming-hub-core.admin.games.index') }}">{{ trans('gaming-hub-core::admin.actions.back_games') }}</a></div>@can('gaminghub.servers.manage')<a class="btn btn-primary" href="{{ route('gaming-hub-core.admin.games.servers.create',$game) }}">{{ trans('gaming-hub-core::admin.actions.create_server') }}</a>@endcan</div>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>{{ trans('gaming-hub-core::admin.fields.order') }}</th><th>{{ trans('gaming-hub-core::admin.fields.server') }}</th><th>{{ trans('gaming-hub-core::admin.fields.slug') }}</th><th>{{ trans('gaming-hub-core::admin.fields.enabled') }}</th><th>{{ trans('gaming-hub-core::admin.fields.public') }}</th><th class="text-end">{{ trans('gaming-hub-core::admin.fields.actions') }}</th></tr></thead><tbody>@forelse($servers as $server)<tr><td>{{ $server->position }}</td><td>{{ $server->name }}</td><td><code>{{ $server->slug }}</code></td><td>{{ trans_bool($server->enabled) }}</td><td>{{ trans_bool($server->public) }}</td><td class="text-end">
<a class="btn btn-sm btn-outline-info" href="{{ route('gaming-hub-core.admin.games.servers.providers.index',[$game,$server]) }}">{{ trans('gaming-hub-core::admin.providers.title') }}</a>
<a class="btn btn-sm btn-outline-secondary" href="{{ route('gaming-hub-core.admin.games.servers.public-data.edit',[$game,$server]) }}">Public Data</a>
@can('gaminghub.servers.manage')
@foreach(['up','down'] as $d)<form class="d-inline" method="POST" action="{{ route('gaming-hub-core.admin.games.servers.move',[$game,$server,$d]) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary">{{ $d==='up'?'↑':'↓' }}</button></form>@endforeach
<form class="d-inline" method="POST" action="{{ route('gaming-hub-core.admin.games.servers.toggle',[$game,$server]) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-warning"><i class="bi bi-power"></i></button></form>
<form class="d-inline" method="POST" action="{{ route('gaming-hub-core.admin.games.servers.duplicate',[$game,$server]) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary"><i class="bi bi-copy"></i></button></form>
<a class="btn btn-sm btn-outline-primary" href="{{ route('gaming-hub-core.admin.games.servers.edit',[$game,$server]) }}"><i class="bi bi-pencil"></i></a>
<form class="d-inline" method="POST" action="{{ route('gaming-hub-core.admin.games.servers.destroy',[$game,$server]) }}" onsubmit="return confirm('{{ trans('gaming-hub-core::admin.server_messages.confirm_delete') }}')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form>@endcan</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">{{ trans('gaming-hub-core::admin.server_messages.empty') }}</td></tr>@endforelse</tbody></table></div></div></div>@endsection