<?php
return [
 'nav'=>['title'=>'Gaming Hub','games'=>'Spiele','directory_settings'=>'Verzeichnis-Einstellungen','public_data'=>'Öffentliche Daten','package_manager'=>'Paketverwaltung'],
 'permissions'=>['games_view'=>'Spielregister anzeigen','games_manage'=>'Spielregister verwalten','servers_view'=>'Server anzeigen','servers_manage'=>'Server verwalten','providers_view'=>'Server-Provider anzeigen','providers_manage'=>'Server-Provider verwalten','settings_manage'=>'Spieleverzeichnis verwalten'],
 'games'=>['title'=>'Spiele','create'=>'Spiel erstellen','edit'=>'Spiel bearbeiten'],
 'servers'=>['title'=>'Server','for_game'=>'Server für :game','create'=>'Server erstellen','edit'=>'Server bearbeiten'],
 'providers'=>['title'=>'Provider','for_game'=>'Provider für :game','for_server'=>'Provider für :server','create'=>'Provider erstellen','edit'=>'Provider bearbeiten'],
 'settings'=>['title'=>'Spieleverzeichnis-Einstellungen','saved'=>'Einstellungen gespeichert.','page_title'=>'Seitentitel','description'=>'Beschreibung','description_help'=>'Nur Klartext; HTML wird maskiert.','columns'=>'Spalten','density'=>'Kartendichte','width'=>'Containerbreite','show_description'=>'Beschreibungen anzeigen','show_status'=>'Status anzeigen','show_provider_message'=>'Provider-Nachricht anzeigen','show_button'=>'Button anzeigen','show_count'=>'Spielanzahl anzeigen','show_servers'=>'Server auf Spielseite anzeigen','game_page_title'=>'Spielseiten-Einstellungen','server_density'=>'Serverkarten-Dichte','server_columns'=>'Serverraster-Spalten','show_server_descriptions'=>'Serverbeschreibungen anzeigen','game_page_show_status'=>'Serverstatus anzeigen','game_page_show_provider_message'=>'Provider-Meldung anzeigen','show_join_button'=>'Beitreten-Schaltfläche anzeigen','show_address'=>'Adresse anzeigen','show_game_navigation'=>'Spielnavigation rechts anzeigen','fallback'=>'Fallback ohne Banner','values'=>['compact'=>'Kompakt','standard'=>'Standard','normal'=>'Normal','wide'=>'Breit','full'=>'Voll','fallback_compact'=>'Kompakte Karte','address_hidden'=>'Ausgeblendet','address_hostname'=>'Nur Hostname','address_hostname_and_port'=>'Hostname und Port','fallback_media'=>'Medien-Platzhalter']],
 'manual'=>['name'=>'Manuell','description'=>'Lokal gepflegter Serverstatus.','status'=>'Status','display_message'=>'Optionale Nachricht'],
 'fields'=>['order'=>'Reihenfolge','game'=>'Spiel','server'=>'Server','name'=>'Name','short_name'=>'Kurzname','slug'=>'Slug','description'=>'Beschreibung','short_description'=>'Kurzbeschreibung','long_description'=>'Lange Beschreibung','icon_url'=>'Icon-URL','banner_url'=>'Banner-URL','accent_color'=>'Akzentfarbe','enabled'=>'Aktiviert','public'=>'Öffentlich','sort_order'=>'Sortierung','hostname'=>'Hostname','display_port'=>'Anzeige-Port','join_url'=>'Beitritts-URL','icon_media_id'=>'Icon-Medien-ID','cover_media_id'=>'Cover-Medien-ID','provider_type'=>'Provider-Typ','actions'=>'Aktionen'],
 'actions'=>['create'=>'Spiel erstellen','create_server'=>'Server hinzufügen','create_provider'=>'Provider hinzufügen','save'=>'Speichern','cancel'=>'Abbrechen','back_games'=>'Zurück zu Spielen','back_servers'=>'Zurück zu Servern'],
 'messages'=>['created'=>'Spiel erstellt.','updated'=>'Spiel aktualisiert.','deleted'=>'Spiel gelöscht.','empty'=>'Keine Spiele registriert.','confirm_delete'=>'Spiel dauerhaft löschen?'],
 'server_messages'=>['created'=>'Server erstellt.','updated'=>'Server aktualisiert.','deleted'=>'Server gelöscht.','duplicated'=>'Server-Metadaten dupliziert; Provider wurden nicht kopiert.','empty'=>'Keine Server vorhanden.','confirm_delete'=>'Server samt Provider-Zuweisungen löschen?'],
 'provider_messages'=>['created'=>'Provider erstellt.','updated'=>'Provider aktualisiert.','moved'=>'Provider-Priorität aktualisiert.','deleted'=>'Provider gelöscht.','empty'=>'Keine Provider diesem Server zugewiesen.','no_types'=>'Keine Provider-Typen verfügbar.','confirm_delete'=>'Provider löschen?','move_boundary'=>'Dieser Provider befindet sich bereits an der angeforderten Grenze.','create_failed'=>'Der Provider konnte nicht erstellt werden.','update_failed'=>'Der Provider konnte nicht aktualisiert werden.','toggle_failed'=>'Der Aktivierungsstatus des Providers konnte nicht geändert werden.','move_failed'=>'Die Provider-Priorität konnte nicht geändert werden.','delete_failed'=>'Der Provider konnte nicht gelöscht werden. Seine Konfiguration und zugehörige Verbindungen wurden nicht verändert.'],
 'validation'=>['unknown_type'=>'Provider-Typ ist nicht registriert.','unavailable_type'=>'Provider-Typ ist nicht verfügbar.','configuration_object'=>'Konfiguration muss ein Objekt sein.','unknown_keys'=>'Unbekannte Schlüssel: :keys'],
];
